import { NextRequest, NextResponse } from 'next/server';
import { scryptSync, timingSafeEqual } from 'crypto';
import {
  signAccessToken,
  signRefreshToken,
  COOKIE_ACCESS,
  COOKIE_REFRESH,
  ACCESS_COOKIE_OPTS,
  REFRESH_COOKIE_OPTS,
  type Role,
} from '@/lib/auth';
import { checkRateLimit, rateLimitHeaders } from '@/lib/rateLimit';

// Force Node.js runtime for crypto.scryptSync
export const runtime = 'nodejs';

// ── User store (from .env.local) ───────────────────────────────────────────
interface User {
  id:           string;
  username:     string;
  passwordHash: string;   // format: salt:hash (hex), generated by scripts/setup-auth.mjs
  role:         Role;
}

function getUsers(): User[] {
  try {
    return JSON.parse(process.env.AUTH_USERS_JSON ?? '[]');
  } catch {
    console.error('[auth/login] AUTH_USERS_JSON inválido ou ausente no .env.local');
    return [];
  }
}

// ── Password verification (scrypt, Node.js built-in) ──────────────────────
function verifyPassword(password: string, stored: string): boolean {
  const parts = stored.split(':');
  if (parts.length !== 2) return false;
  const [salt, hash] = parts;
  try {
    const derived = scryptSync(password, salt, 64);
    return timingSafeEqual(Buffer.from(hash, 'hex'), derived);
  } catch {
    return false;
  }
}

// ── POST /api/auth/login ───────────────────────────────────────────────────
export async function POST(req: NextRequest) {
  // Brute-force protection: 10 attempts per IP in 5-minute window
  const ip = req.headers.get('x-forwarded-for')?.split(',')[0].trim() ?? '127.0.0.1';
  const rl = checkRateLimit(`login:${ip}`, 10, 5 * 60_000);

  if (!rl.ok) {
    return NextResponse.json(
      { error: 'Muitas tentativas. Aguarde alguns minutos antes de tentar novamente.' },
      { status: 429, headers: rateLimitHeaders(rl, 10) }
    );
  }

  // Parse body
  let username: string | undefined;
  let password: string | undefined;
  try {
    const body = await req.json();
    username = body?.username;
    password = body?.password;
  } catch {
    return NextResponse.json({ error: 'Corpo da requisição inválido' }, { status: 400 });
  }

  if (!username || !password) {
    return NextResponse.json({ error: 'Usuário e senha são obrigatórios' }, { status: 400 });
  }

  // Find user & verify password
  const users = getUsers();
  const user  = users.find(u => u.username === username);

  // Always run verifyPassword even when user is not found (timing-safe)
  const dummyHash = 'abc:abc';
  const valid     = user ? verifyPassword(password, user.passwordHash) : verifyPassword(password, dummyHash);

  if (!user || !valid) {
    // Deliberate generic message (don't reveal which field is wrong)
    return NextResponse.json({ error: 'Usuário ou senha incorretos' }, { status: 401 });
  }

  // Issue tokens
  const tokenBase = { sub: user.id, username: user.username, role: user.role };
  const [accessToken, refreshToken] = await Promise.all([
    signAccessToken(tokenBase),
    signRefreshToken(tokenBase),
  ]);

  const res = NextResponse.json({
    user: { id: user.id, username: user.username, role: user.role },
  });

  res.cookies.set(COOKIE_ACCESS,  accessToken,  ACCESS_COOKIE_OPTS);
  res.cookies.set(COOKIE_REFRESH, refreshToken, REFRESH_COOKIE_OPTS);

  return res;
}
